version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: findify/circleci-node-container

commands:
  deploy-to-s3:
    description: Deploy bundle to s3
    steps:
      - run:
          name: Deploy << parameters.env >>
          command: |
            export PKG_NAME=bundle
            export PKG_BUNDLE_DIR=dist
            export DST_BUNDLE_DIR=bundle/staging/$CIRCLE_BRANCH
            export S3_BUCKET_PATH=findify-assets
            export SRC_BUNDLE_PATH=packages/$PKG_NAME/$PKG_BUNDLE_DIR
            export DST_BUNDLE_PATH=$S3_BUCKET_PATH/$DST_BUNDLE_DIR
            echo "deploying $SRC_BUNDLE_PATH to s3://$DST_BUNDLE_PATH"
            aws s3 cp --recursive $SRC_BUNDLE_PATH s3://$DST_BUNDLE_PATH

jobs:
  build_and_test:
    <<: *defaults

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install deps
          command: yarn

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: build
          command: yarn build:dist

      - persist_to_workspace:
          root: ~/repo
          paths:
            - '*'

  deploy:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/repo

      - deploy-to-s3:

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
          filters:
            branches:
              only:
                - master
                - /^([0-9]+\.[0-9]+\.[0-9]+)?$/