version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: findify/circleci-node-container

jobs:
  build_and_test:
    <<: *defaults

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install deps
          command: yarn

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: build
          command: yarn build:dist

      - persist_to_workspace:
          root: ~/repo
          paths:
            - '*'

  deploy:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: init command
          command: echo "DEPLOY"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
          filters:
            branches:
              only:
                - master
                - /^([0-9]+\.[0-9]+\.[0-9]+)?$/