version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: findify/circleci-node-container

jobs:
  build_and_test:
    <<: *defaults

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
            
      - run:
          name: setup env variables
          command: |
            [ "$CIRCLE_BRANCH" = master ] && echo 'export PUBLIC_PATH=https://cdn.jsdelivr.net/npm/@findify/bundle@__MERCHANT_VERSION_RAW__/dist/' >> $BASH_ENV || echo 'export PUBLIC_PATH=https://findify-assets-2bveeb6u8ag.netdna-ssl.com/bundle/staging/__MERCHANT_VERSION_RAW__/' >> $BASH_ENV
            [ "$CIRCLE_BRANCH" = master ] && echo 'export FINDIFY_ENV=production' >> $BASH_ENV || echo 'export FINDIFY_ENV=staging' >> $BASH_ENV

      - run:
          name: install deps
          command: yarn

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: setup node env
          command: echo 'export NODE_ENV=production' >> $BASH_ENV

      - run:
          name: build
          command: yarn build:dist

      - persist_to_workspace:
          root: ~/repo
          paths:
            - '*'

  deploy-to-s3:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Deploy to s3
          command: |
            export PKG_NAME=bundle
            export PKG_BUNDLE_DIR=dist
            export DST_BUNDLE_DIR=bundle/staging/$CIRCLE_BRANCH
            export S3_BUCKET_PATH=findify-assets
            export SRC_BUNDLE_PATH=packages/$PKG_NAME/$PKG_BUNDLE_DIR
            export DST_BUNDLE_PATH=$S3_BUCKET_PATH/$DST_BUNDLE_DIR
            echo "deploying $SRC_BUNDLE_PATH to s3://$DST_BUNDLE_PATH"
            aws s3 cp --recursive $SRC_BUNDLE_PATH s3://$DST_BUNDLE_PATH

  publish-to-npm:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/repo
      
      - run:
          name: configure npm auth creds
          command: npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN -q

      - add_ssh_keys:
          fingerprints:
            - "f3:a5:7e:33:ac:e6:1a:9e:82:29:34:b7:34:37:08:2d"

      - run:
          name: update git auth creds
          command: |
            git config --global user.email "infra@findify.io"
            git config --global user.name "findify-bot"

      - run:
          name: Publish bundles to npm
          command: npx lerna publish --yes

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_test
      - deploy-to-s3:
          requires:
            - build_and_test
          context:
            - backend
          filters:
            branches:
              only:
                - /^([0-9]+\.[0-9]+\.[0-9]+)?$/
      - publish-to-npm:
          requires:
            - build_and_test
          context:
            - backend
          filters:
            branches:
              only:
                - master